remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Xiyin Deng]
description: [a student in SWUFE-UD and this is my personal website]
show_downloads: ['true']